version: '3.8'
services:
  backend: 
    container_name: backend
    build: ./backend/
    restart: unless-stopped
    command: ["sh", "-c", "sleep 10 && uvicorn main:app --host 0.0.0.0 --port 3000"]
    ports:
      - 3000:3000
    depends_on: 
      - database
  
  database:
    build: ./mysql/
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=2003
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=resumer
      - MYSQL_USER=anmol 
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql : 
    driver: local
